name=input("enter your name:")
branch=input("enter your branch:")
gender=input("enter your gender:")
collegename=input("enter your college name:")
age=int(input("enter your age:"))
print("name:",name)
print("branch:",branch)
print("gender:",gender)
print("college name;",collegename)
print("age:",age)
